### ISSUE TITLE
Roadmap: v1

### ISSUE THREAD

**Issue by DaanGamesDG** [DaanGamesDG/website#4]
### To Do List:
- [x] General
  - [x] File structure Cleanup (#23)
  - [x] Updated Readme (#22)
  - [x] Guides (https://github.com/DaanGamesDG/website/wiki/)
    - [x] Self hosting guide
    - [x] Config explantion guide
    - [x] Home page
- [x] Misc
  - [x] Lanyard (#2)
  - [x] Configurable options (#21)
  - [x] Page transitions (#20)
  - [x] Meta data (redirect links, meta head tags, etc) (#19)
- [x] Components
  - [x] Navbar (#3)
  - [x] Buttons (#5) (part of it in #3)
  - [x] Footer (#11)
    - [x] Add credits (#18)
  - [x] Anime List (part of #10)
- [x] Pages
  - [x] Home Page (#9)
  - [x] About Me Page (#10)
    - [x] More information (#12)
  - [x] Stats Page (#13)
    - [x] More information: code time (#15)
  - [x] 404 Page (#16)
- [x] Api
  - [x] Facts API (#14)

**Comment by DaanGamesDG** [comment]
All tasks completed ✅
